package org.ionc.wallet.greendaogen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.ionc.wallet.bean.TxRecordBean;
import org.ionc.wallet.bean.WalletBean;
import org.ionc.wallet.bean.WalletBeanNew;
import org.ionc.wallet.bean.TxRecordBeanAllHelper;
import org.ionc.wallet.bean.TxRecordBeanInHelper;
import org.ionc.wallet.bean.TxRecordBeanOutHelper;

import org.ionc.wallet.greendaogen.TxRecordBeanDao;
import org.ionc.wallet.greendaogen.WalletBeanDao;
import org.ionc.wallet.greendaogen.WalletBeanNewDao;
import org.ionc.wallet.greendaogen.TxRecordBeanAllHelperDao;
import org.ionc.wallet.greendaogen.TxRecordBeanInHelperDao;
import org.ionc.wallet.greendaogen.TxRecordBeanOutHelperDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig txRecordBeanDaoConfig;
    private final DaoConfig walletBeanDaoConfig;
    private final DaoConfig walletBeanNewDaoConfig;
    private final DaoConfig txRecordBeanAllHelperDaoConfig;
    private final DaoConfig txRecordBeanInHelperDaoConfig;
    private final DaoConfig txRecordBeanOutHelperDaoConfig;

    private final TxRecordBeanDao txRecordBeanDao;
    private final WalletBeanDao walletBeanDao;
    private final WalletBeanNewDao walletBeanNewDao;
    private final TxRecordBeanAllHelperDao txRecordBeanAllHelperDao;
    private final TxRecordBeanInHelperDao txRecordBeanInHelperDao;
    private final TxRecordBeanOutHelperDao txRecordBeanOutHelperDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        txRecordBeanDaoConfig = daoConfigMap.get(TxRecordBeanDao.class).clone();
        txRecordBeanDaoConfig.initIdentityScope(type);

        walletBeanDaoConfig = daoConfigMap.get(WalletBeanDao.class).clone();
        walletBeanDaoConfig.initIdentityScope(type);

        walletBeanNewDaoConfig = daoConfigMap.get(WalletBeanNewDao.class).clone();
        walletBeanNewDaoConfig.initIdentityScope(type);

        txRecordBeanAllHelperDaoConfig = daoConfigMap.get(TxRecordBeanAllHelperDao.class).clone();
        txRecordBeanAllHelperDaoConfig.initIdentityScope(type);

        txRecordBeanInHelperDaoConfig = daoConfigMap.get(TxRecordBeanInHelperDao.class).clone();
        txRecordBeanInHelperDaoConfig.initIdentityScope(type);

        txRecordBeanOutHelperDaoConfig = daoConfigMap.get(TxRecordBeanOutHelperDao.class).clone();
        txRecordBeanOutHelperDaoConfig.initIdentityScope(type);

        txRecordBeanDao = new TxRecordBeanDao(txRecordBeanDaoConfig, this);
        walletBeanDao = new WalletBeanDao(walletBeanDaoConfig, this);
        walletBeanNewDao = new WalletBeanNewDao(walletBeanNewDaoConfig, this);
        txRecordBeanAllHelperDao = new TxRecordBeanAllHelperDao(txRecordBeanAllHelperDaoConfig, this);
        txRecordBeanInHelperDao = new TxRecordBeanInHelperDao(txRecordBeanInHelperDaoConfig, this);
        txRecordBeanOutHelperDao = new TxRecordBeanOutHelperDao(txRecordBeanOutHelperDaoConfig, this);

        registerDao(TxRecordBean.class, txRecordBeanDao);
        registerDao(WalletBean.class, walletBeanDao);
        registerDao(WalletBeanNew.class, walletBeanNewDao);
        registerDao(TxRecordBeanAllHelper.class, txRecordBeanAllHelperDao);
        registerDao(TxRecordBeanInHelper.class, txRecordBeanInHelperDao);
        registerDao(TxRecordBeanOutHelper.class, txRecordBeanOutHelperDao);
    }
    
    public void clear() {
        txRecordBeanDaoConfig.clearIdentityScope();
        walletBeanDaoConfig.clearIdentityScope();
        walletBeanNewDaoConfig.clearIdentityScope();
        txRecordBeanAllHelperDaoConfig.clearIdentityScope();
        txRecordBeanInHelperDaoConfig.clearIdentityScope();
        txRecordBeanOutHelperDaoConfig.clearIdentityScope();
    }

    public TxRecordBeanDao getTxRecordBeanDao() {
        return txRecordBeanDao;
    }

    public WalletBeanDao getWalletBeanDao() {
        return walletBeanDao;
    }

    public WalletBeanNewDao getWalletBeanNewDao() {
        return walletBeanNewDao;
    }

    public TxRecordBeanAllHelperDao getTxRecordBeanAllHelperDao() {
        return txRecordBeanAllHelperDao;
    }

    public TxRecordBeanInHelperDao getTxRecordBeanInHelperDao() {
        return txRecordBeanInHelperDao;
    }

    public TxRecordBeanOutHelperDao getTxRecordBeanOutHelperDao() {
        return txRecordBeanOutHelperDao;
    }

}
