package org.ionc.wallet.greendaogen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import org.ionc.wallet.bean.TxRecordBeanInHelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TX_RECORD_BEAN_IN_HELPER".
*/
public class TxRecordBeanInHelperDao extends AbstractDao<TxRecordBeanInHelper, Long> {

    public static final String TABLENAME = "TX_RECORD_BEAN_IN_HELPER";

    /**
     * Properties of entity TxRecordBeanInHelper.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IndexMaxForIn = new Property(1, Long.class, "indexMaxForIn", false, "INDEX_MAX_FOR_IN");
        public final static Property ToAddress = new Property(2, String.class, "toAddress", false, "TO_ADDRESS");
    }


    public TxRecordBeanInHelperDao(DaoConfig config) {
        super(config);
    }
    
    public TxRecordBeanInHelperDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TX_RECORD_BEAN_IN_HELPER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"INDEX_MAX_FOR_IN\" INTEGER," + // 1: indexMaxForIn
                "\"TO_ADDRESS\" TEXT);"); // 2: toAddress
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TX_RECORD_BEAN_IN_HELPER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TxRecordBeanInHelper entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long indexMaxForIn = entity.getIndexMaxForIn();
        if (indexMaxForIn != null) {
            stmt.bindLong(2, indexMaxForIn);
        }
 
        String toAddress = entity.getToAddress();
        if (toAddress != null) {
            stmt.bindString(3, toAddress);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TxRecordBeanInHelper entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long indexMaxForIn = entity.getIndexMaxForIn();
        if (indexMaxForIn != null) {
            stmt.bindLong(2, indexMaxForIn);
        }
 
        String toAddress = entity.getToAddress();
        if (toAddress != null) {
            stmt.bindString(3, toAddress);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TxRecordBeanInHelper readEntity(Cursor cursor, int offset) {
        TxRecordBeanInHelper entity = new TxRecordBeanInHelper( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // indexMaxForIn
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // toAddress
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TxRecordBeanInHelper entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIndexMaxForIn(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setToAddress(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TxRecordBeanInHelper entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TxRecordBeanInHelper entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TxRecordBeanInHelper entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
