package org.ionc.wallet.greendaogen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import org.ionc.wallet.bean.TxRecordBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TX_RECORD_BEAN".
*/
public class TxRecordBeanDao extends AbstractDao<TxRecordBean, Long> {

    public static final String TABLENAME = "TX_RECORD_BEAN";

    /**
     * Properties of entity TxRecordBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Block = new Property(1, String.class, "block", false, "BLOCK");
        public final static Property TxHash = new Property(2, String.class, "txHash", false, "TX_HASH");
        public final static Property TxFee = new Property(3, String.class, "txFee", false, "TX_FEE");
        public final static Property From = new Property(4, String.class, "from", false, "FROM");
        public final static Property To = new Property(5, String.class, "to", false, "TO");
        public final static Property Value = new Property(6, String.class, "value", false, "VALUE");
    }


    public TxRecordBeanDao(DaoConfig config) {
        super(config);
    }
    
    public TxRecordBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TX_RECORD_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BLOCK\" TEXT," + // 1: block
                "\"TX_HASH\" TEXT," + // 2: txHash
                "\"TX_FEE\" TEXT," + // 3: txFee
                "\"FROM\" TEXT," + // 4: from
                "\"TO\" TEXT," + // 5: to
                "\"VALUE\" TEXT);"); // 6: value
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TX_RECORD_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TxRecordBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String block = entity.getBlock();
        if (block != null) {
            stmt.bindString(2, block);
        }
 
        String txHash = entity.getTxHash();
        if (txHash != null) {
            stmt.bindString(3, txHash);
        }
 
        String txFee = entity.getTxFee();
        if (txFee != null) {
            stmt.bindString(4, txFee);
        }
 
        String from = entity.getFrom();
        if (from != null) {
            stmt.bindString(5, from);
        }
 
        String to = entity.getTo();
        if (to != null) {
            stmt.bindString(6, to);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(7, value);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TxRecordBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String block = entity.getBlock();
        if (block != null) {
            stmt.bindString(2, block);
        }
 
        String txHash = entity.getTxHash();
        if (txHash != null) {
            stmt.bindString(3, txHash);
        }
 
        String txFee = entity.getTxFee();
        if (txFee != null) {
            stmt.bindString(4, txFee);
        }
 
        String from = entity.getFrom();
        if (from != null) {
            stmt.bindString(5, from);
        }
 
        String to = entity.getTo();
        if (to != null) {
            stmt.bindString(6, to);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(7, value);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TxRecordBean readEntity(Cursor cursor, int offset) {
        TxRecordBean entity = new TxRecordBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // block
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // txHash
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // txFee
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // from
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // to
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // value
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TxRecordBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBlock(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTxHash(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTxFee(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFrom(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTo(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setValue(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TxRecordBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TxRecordBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TxRecordBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
